# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-johnblue"
BBFILE_PATTERN_meta-johnblue = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-johnblue = "10"

LAYERDEPENDS_meta-johnblue = "core phosphor-layer aspeed-layer meta-evb-ast2600"

LAYERSERIES_COMPAT_meta-johnblue = "wrynose whinlatter"
